services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # map port 5000 on host to container
    env_file:
      - ./backend/.env # Loads environment variables for the backend
    volumes:  
      - ./backend/database.sqlite:/usr/src/app/database.sqlite # Maps SQLite database
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your_jwt_secret
    command: npm start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000 